---
- hosts: all
  become: true
  tasks:
    - name: Make sure the remote app root exists and has the right permissions
      file:
        path: "{{ remote_www_root }}/{{ app_root_dir }}"
        state: directory
        mode: '0755'

    - name: Rsync application files to the remote server
      synchronize:
        src: "application/{{ app_root_dir }}"
        dest: "{{ remote_www_root }}"
        rsync_opts:
          - "--no-motd"
          - "--exclude=.git,vendor,tests,storage/logs/*,storage/framework/sessions/*,storage/framework/cache/*"

    - name: Set up additional directory permissions for www-data user on storage folder
      acl:
        path: "{{ remote_www_root }}/{{ app_root_dir }}/storage/"
        entry: group:www-data:rwX
        recursive: yes
        state: present

    - name: Set up additional directory permissions for www-data user on bootstrap/cache folder
      acl:
        path: "{{ remote_www_root }}/{{ app_root_dir }}/bootstrap/cache/"
        entry: group:www-data:rwX
        recursive: yes
        state: present
    # PHP Info Page
    - name: Sets Up PHP Info Page
      template:
        src: "files/info.php.j2"
        dest: "/var/www/{{ app_root_dir }}/public/info.php"

    - name: Delete content & directory
      shell: /bin/rm -rf /var/www/{{ app_root_dir }}/composer.lock


    - name: Install Dependencies with Composer
      become: false
      composer:
        command: install
        working_dir: "{{ remote_www_root }}/{{ app_root_dir }}"
        no_dev: no
      environment:
        COMPOSER_ALLOW_SUPERUSER: 1

    - name: Install Project
      become: false
      composer:
        command: create-project
        no_dev: no
        working_dir: "{{ remote_www_root }}/{{ app_root_dir }}"
      environment:
        COMPOSER_ALLOW_SUPERUSER: 1
      

    - name: Run Migrations + Seeders
      command: "/usr/bin/php {{ remote_www_root }}/{{ app_root_dir }}/artisan migrate --seed"
      environment:
        COMPOSER_ALLOW_SUPERUSER: 1
      
    # - name: Run artisan migrate
    #   shell: php {{ remote_www_root }}/{{ app_root_dir }}/artisan migrate:feed
    #   environment:
    #     COMPOSER_ALLOW_SUPERUSER: 1

    - name: Disable default Apache site
      shell: /usr/sbin/a2dissite 000-default.conf
      when: disable_default
      notify: Reload Apache  


    - name: Enable new site
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: Restart Apache  

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted