---
- hosts: all
  become: true
  tasks:
    - name: Copy script
      become: true
      copy:
        src: "scripts/postgress.sh"
        dest: "/home/root"

    - name: Execute the script 
      script: scripts/postgress.sh